### PR TITLE
Add environment variable token provider.

### LINKED ISSUE #2863: Environment variable ID token detection
**Description**

I'd like to propose adding environment variable OIDC token detection for cosign.

Main use case is to support [GitLab CI OIDC tokens](https://docs.gitlab.com/ee/ci/secrets/id_token_authentication.html) - see https://github.com/sigstore/fulcio/pull/983 for more details.

## Proposal

Today, users can already use arbitrary OIDC tokens by using the `--identity-token` flag.

```sh
cosign sign --identity-token=${TOKEN} ...
```

To make this easier, I want to allow cosign to detect a token from environment variables.
To help avoid collisions with existing token variables, we should use a prefixed value such as `SIGSTORE_ID_TOKEN`.

This could also be used to allow other CI providers to hook in without needing additional changes to cosign (though I'm still in support for allowing custom providers per host).

Example: GitLab

```
build:
  stage: build
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
     - cosign sign registry.gitlab.com/my-image
```

I'm happy to implement this.

Previous GitLab related issues:
- https://github.com/sigstore/cosign/issues/2697
- https://github.com/sigstore/cosign/issues/1254

### PR DESCRIPTION
**Pull request by wlynch**
#### Summary

This adds a new token provider that looks for tokens located at `SIGSTORE_ID_TOKEN`.

This is an alternative to `COSIGN_IDENTITY_TOKEN`, which is [implemented as a Viper binding](https://github.com/sigstore/cosign/pull/2346).

`ID_TOKEN` was used instead of `IDENTITY_TOKEN`, since this seems to be consistent with other providers (e.g. `ACTIONS_ID_TOKEN_REQUEST_TOKEN`). If this ends up being confusing we can add support for both variants later if needed.

Fixes #2863, #2697, #1254 

#### Release Note

* Added new token provider for looking up OIDC tokens in the `SIGSTORE_ID_TOKEN` environment variable.

#### Documentation

Should docs be added before this is actually released and available to people? 🤔 
(it would be great if we could base the docs on cosign versions)

### CODE REVIEW

**Comment by haydentherapper** [comment]
Why does this solve the GitLab provider issue? Does GitLab let you control which environment variable its ID token is written to, in contrast to the other CI providers which have predefined, fixed env vars?

**Comment by wlynch** [comment]
> Why does this solve the GitLab provider issue? Does GitLab let you control which environment variable its ID token is written to, in contrast to the other CI providers which have predefined, fixed env vars?

Yup! Exactly. So you should be able to do something like this:

```yaml
build:
  stage: build
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
     - cosign sign ...
```

**Comment by haydentherapper** [comment]
Sweet, thanks for clarifying! 

Can you also update pkg/providers/all/all.go?

**Comment by haydentherapper** [comment]
After this is in, we'll cut Cosign 2.0.1

**Review by hectorj2f — APPROVED** [review]

**Comment by hectorj2f** [comment]
Yes, I'd say we need a section to describe our available environment variables.

**Review by hectorj2f — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Pull request merged**
