### PR TITLE
Eliminate `AttachedImageTag` in favor of `ociremote` variants.

### PR DESCRIPTION
**Pull request by mattmoor**
We were starting to accumulate a large number of variants of this method, which all do roughly equivalent things.

This change consolidates around a handful of methods in the `ociremote` package oriented around the kind of attachment they represent.
 * `ociremote.SignatureTag(ref, opts...)` produces the tag for referencing attached signatures.
 * `ociremote.AttestationTag(ref, opts...)` produces the tag for referencing attached attestations.
 * `ociremote.SBOMTag(ref, opts...)` produces the tag for referencing attached SBOMs.

These share some core logic to be efficient, but they:
1. Check whether they were passed a digest,
2. If not, resolves the digest using the supplied options,
3. Construct the final tag based on the options (e.g. target repo) and the resolved or passed digest.

Signed-off-by: Matt Moore <mattomata@gmail.com>

#### Ticket Link
Related: https://github.com/sigstore/cosign/issues/666

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by mattmoor** [comment]
cc @n3wscott since you just introduced this 😅

**Comment by mattmoor** [comment]
This also eliminates `TargetRepositoryForImage` and drops the error returned by `ociremote.Option`.  The last bit should be a non-issue since only this package can define or consume them since `*options` is private.

**Comment by n3wscott** [comment]
I just moved it, I have no ... Attachment to it

**Comment by mattmoor** [comment]
> I just moved it, I have no ... Attachment to it

ZING!

**Review by dekkagaijin — APPROVED** [review]

**Pull request merged**
