### PR TITLE
added autocompletion support to cosign

### PR DESCRIPTION
**Pull request by developer-guy**
https://user-images.githubusercontent.com/16693043/126901892-ffbee375-3d5d-4fdc-9b87-7c854ca63d29.mov

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

I tried to add autocompletion support for `cosign` for `zsh`, but I know this code is pretty bad, so we have to improve it someway but at least it is the beginning of the process of autocompletion support.

### CODE REVIEW

**Comment by n3wscott** [comment]
when we move to cobra, this becomes very simple.

**Comment by developer-guy** [comment]
> when we move to cobra, this becomes very simple.

yes, that's right. @n3wscott 

```golang
var CompletionCmd = &cobra.Command{
    Use:   "completion [bash|zsh|fish|powershell]",
    Short: "Generate completion script",
    Long: "To load completions",
    DisableFlagsInUseLine: true,
    ValidArgs:             []string{"bash", "zsh", "fish", "powershell"},
    Args:                  cobra.ExactValidArgs(1),
    Run: func(cmd *cobra.Command, args []string) {
        switch args[0] {
        case "bash":
            cmd.Root().GenBashCompletion(os.Stdout)
        case "zsh":
            cmd.Root().GenZshCompletion(os.Stdout)
        case "fish":
            cmd.Root().GenFishCompletion(os.Stdout, true)
        case "powershell":
            cmd.Root().GenPowerShellCompletionWithDesc(os.Stdout)
        }
    },
}
```

**Comment by dekkagaijin** [comment]
Thanks @developer-guy, sorry I didn't see this earlier 😅

Mind changing this PR to integrate with cobra?

**Comment by developer-guy** [comment]
> Thanks @developer-guy, sorry I didn't see this earlier 😅
> 
> Mind changing this PR to integrate with cobra?

no problem @dekkagaijin, I really would want to integrate it when cosign started to use Cobra 😋

**Comment by developer-guy** [comment]
@n3wscott may I add this support, can you please assign this issue to me 😍🤩🤝

**Comment by n3wscott** [comment]
Yes yes! Please do!!

**Comment by developer-guy** [comment]
@n3wscott we can close this one, and continue from #836 🤝 🙋🏻‍♂️

**Pull request closed without merging**
