### PR TITLE
Add example using AWS Key Management Service (KMS)

### PR DESCRIPTION
**Pull request by davivcgarcia**
#### Summary

This PR adds an example on how to leverage AWS KMS using AWS CLI (`aws`) to sign and verify signatures handled by `cosign`.

#### Ticket Link
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by dlorenc** [comment]
This is awesome! Thanks for the contribution!

**Comment by dlorenc** [comment]
Looks like you need the DCO bit - you can fix that with something like `git commit -s --amend` and then `git push -f`

**Review by cpanato — COMMENTED** [review]
looks great! thanks for that

just sign the DCO and remove the extra line and we are good to go

**Comment by dlorenc** [comment]
Closing, please reopen if you get DCO working!

**Comment by davivcgarcia** [comment]
Sorry folks the delay, for some reason I missed this notification. I already rebased to main, and fixed DCO and trailing whitespace.

**Comment by dlorenc** [comment]
Hmm, I can't reopen it either... You might have to open a new one from the same branch.

**Comment by davivcgarcia** [comment]
No problem! I'll open a new PR. Sorry for this inconvenience.

**Pull request closed without merging**
