### PR TITLE
Add certificate chain flag for signing

### PR DESCRIPTION
**Pull request by haydentherapper**
This allows users to pass their own certificate chain to include in the
OCI signature. The chain is checked for validity using the provided
certificate.

Also refactored the check for matching public keys using a method from
sigstore/sigstore, comparing the certificate's key with the provided
key. Also added this check when extracting the PKCS11 certificate.

Certificate chains must be PEM-encoded. I changed the text of the
certificate flag to also specify a preference for PEM encoding, but
didn't remove the code that handles DER encoding for backwards
compatibility.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

#### Ticket Link

Ref #1554

#### Release Note

```release-note
Added cert-chain flag for including certificate chain in OCI signature on signing
```

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @bburky @dlorenc

**Comment by haydentherapper** [comment]
@dlorenc Are you familiar with `./hack/update-codegen.sh`? I ran it, but it had a few errors, and ended up generating a bunch of code files in `vendors/` rather than updating the licenses.

**Comment by haydentherapper** [comment]
Figured out the issue, looks like some part of the script needs a license binary to be installed via `go install` instead of `go get`.

**Comment by bburky** [comment]
I tested with a couple configurations:
```
# The following works great and adds the chain annotation:
cosign sign --key "awskms:///..." --cert cert.pem  --cert-chain chain.pem "localhost:5000/$image"  
# The following does _not_ work. The certificate is automatically extracted from the smartcard, but the provided chain is not added as an annotation:
cosign sign --key "pkcs11:..."  --cert-chain chain.pem "localhost:5000/$image"  
```

In general, I've noticed the (optional) `--cert` flag doesn't seem to work for `--key "pkcs11:..."` and I think this is the same issue. The cert provided from the token is used unconditionally, the cert on the command line is not used. It should probably be an error to pass `--cert`, or it should be used instead of the one on the token.

Perhaps the `cosign sign --key "pkcs11:..."  --cert-chain chain.pem` behavior is related? It seems that the provided cert chain is ignored.

**Comment by haydentherapper** [comment]
Thanks for testing this out. Currently, with a pkcs11 key, it attempts to fetch a certificate from the token and then returns early. You're correct, it's currently ignoring the cert and cert chain flags. I just need to change it to not exit early.

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
