### PR TITLE
feat: add output cert for keyless

### LINKED ISSUE #936: Using sign-blob with a transparency log should output cert to disk
**Description**

I’m trying to use cosign’s experimental transparency log feature to sign a blob (a go binary built and uploaded to a GH release).
verify-blob requires the blob, signature, and public key.
The blob and signature are easy to provide. (The signature can be extracted when signing via the --signature flag). However getting the public key is a bit trickier...

The sign-blob does output the ephemeral signing cert to stdout. However the only way to extract it is via scripting it out of stdout.

i.e.
```
COSIGN_EXPERIMENTAL=1 cosign sign-blob --output /tmp/sig /tmp/blob  2>&1 | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' > /tmp/crt
```

It would be great if there was a flag to do this instead!

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>

#### Summary

Add ability to output certificate for keyless mode

#### Ticket Link

Fixes #936

#### Release Note

```release-note
feat: add output cert for keyless
```

render1636543302281

### CODE REVIEW

**Comment by developer-guy** [comment]
friendly ping @DennisDenuto 👍

**Comment by developer-guy** [comment]
> That's a duplicate to my PR: #1016

should we close this PR, and move on with #1016? @dlorenc

**Comment by shibumi** [comment]
@developer-guy  I think so. Your PR lives on in my PR :) I "stole" the test change from you.

**Comment by developer-guy** [comment]
> @developer-guy I think so. Your PR lives on in my PR :) I "stole" the test change from you.

Okay then, you beat us this time, we'll see in the next round 🥊

**Pull request closed without merging**
