### PR TITLE
feat(ci): Add GoFish support

### LINKED ISSUE #855: Add GoFish support
**Description**

Hello cosign community and @cpanato,

I added GoFish support via goreleasers (@caarlos0). 

Thanks

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

#### Summary

Hello cosign community and @cpanato,

I added GoFish support via goreleasers (@caarlos0). The only things we need before merging this PR:

A github repo called: fish-food  similar to https://github.com/goreleaser/fish-food and and ensure access to it during the release process.

```yaml
owner: sigstore
name: fish-food
```

#### Ticket Link

Fixes #855 

#### Release Note

NONE
```release-note

```

### CODE REVIEW

**Review by developer-guy — APPROVED** [review]
thank you @dirien for this PR, this looks good. LGTM

**Comment by developer-guy** [comment]
looks like some tests are failing, can you please fix them @dirien 😋

**Comment by cpanato** [comment]
@dlorenc Lets add the Gofish support as well? for that we will need to create this new repository called `fish-food` and then add our bot the permission to push and let me know as well then I can setup the repo with readme and other things

---

@dirien what are the other setup requirements for this repository? can be a clean only with the readme or do we need to do any configuration/commits before?

**Comment by dirien** [comment]
Hi @cpanato , where do you set the version of goreleaser?

**Comment by dlorenc** [comment]
> @dlorenc Lets add the Gofish support as well? for that we will need to create this new repository called `fish-food` and then add our bot the permission to push and let me know as well then I can setup the repo with readme and other things

I can create the repo and give you permissions

**Comment by cpanato** [comment]
> Hi @cpanato , where do you set the version of goreleaser?

what do you mean by that?

**Comment by cpanato** [comment]
repo created and initial setup is done: https://github.com/sigstore/fish-food

thanks Dan!

**Comment by cpanato** [comment]
> @cpanato, ok as long the magic-image is not updateing the goreleaser version, we can't continue here. and the build will fail here too!
> 
> Classic mexican standoff situation...

ok lets wait and drink some margaritas!

/tequila

**Review by caarlos0 — APPROVED** [review]

**Comment by dirien** [comment]
@cpanato: Rebase done!

**Comment by cpanato** [comment]
looks like the in the snapshot running it is not happy, also looking at the goreleaser code it expects a package and we produce a binary, not a .tar.gz/.zip file

**Comment by caarlos0** [comment]
> anything we need to add in the upstream to check that?

hmm, afaik no...

**Comment by caarlos0** [comment]
here we go:

- https://github.com/goreleaser/goreleaser/pull/2576
- https://github.com/goreleaser/goreleaser/pull/2577

**Comment by dirien** [comment]
Can i help somehow? I would like to help :)

**Comment by dirien** [comment]
Hi @cpanato, @caarlos0 released the new version of goreleaser. You could update your base image and then we should come closer to finishing the PR here.

**Comment by cpanato** [comment]
> Hi @cpanato, @caarlos0 released the new version of goreleaser. You could update your base image and then we should come closer to finishing the PR here.

image available tag `v1.17.2-2` :) lets try again

**Comment by dirien** [comment]
Screw my repo had to fork again... :( 

Continues here -> #995

**Pull request closed without merging**
