### PR TITLE
feat: Support basic auth and bearer auth login to registry

### PR DESCRIPTION
**Pull request by tosone**
#### Summary

In some scenarios, user wants to login the registry in oneline command. trivy can be used like this: `trivy image --registry-token xx image`

#### Release Note

Support basic auth and bearer auth login to registry

### CODE REVIEW

**Comment by tosone** [comment]
@haydentherapper Could you please review this pr?

**Review by cpanato — COMMENTED** [review]
it lgtm
but wondering if we can rely on the existing auth like when you do `docker login` ...

**Comment by tosone** [comment]
Yes, `github.com/google/go-containerregistry` can read the auth info from `docker login`, but in some scenarios, I have no the basic auth(username/password) info, only the bearer token, `gcr` also supports bearer token access registry.
I have some code snippets that need this feat. https://github.com/go-sigma/sigma/blob/main/pkg/signing/cosign/sign/sign.go#L82

**Comment by tosone** [comment]
@haydentherapper gently ping.

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
