### PR TITLE
added ability to get image digest back via triangulate

### PR DESCRIPTION
**Pull request by garethahealy**
#### Summary
Provides the ability to resolve digest for image without the need to use another tool, such as crane/skopeo
- https://github.com/sigstore/cosign/issues/3251

Fixes https://github.com/sigstore/cosign/issues/3034

#### Documentation
CLI provides self-documentation via extra option on flag.

### CODE REVIEW

**Comment by haydentherapper** [comment]
@garethahealy Thanks for the PR! Looks good, can you rebase and add a comment that demonstrates this in use?

**Comment by garethahealy** [comment]
rebased

**Comment by garethahealy** [comment]
usage:

```
$ ./cosign triangulate --help
Outputs the located cosign image reference. This is the location cosign stores the specified artifact type.

Usage:
cosign triangulate [flags]

Examples:
  cosign triangulate <IMAGE>

Flags:
    --allow-http-registry=false:
	whether to allow using HTTP protocol while connecting to registries. Don't use this for anything but testing

    --allow-insecure-registry=false:
	whether to allow insecure connections to registries (e.g., with expired or self-signed TLS certificates).
	Don't use this for anything but testing

    --attachment-tag-prefix='':
	optional custom prefix to use for attached image tags. Attachment images are tagged as:
	`[AttachmentTagPrefix]sha256-[TargetImageDigest].[AttachmentName]`

    -h, --help=false:
	help for triangulate

    --k8s-keychain=false:
	whether to use the kubernetes keychain instead of the default keychain (supports workload identity).

    --type='signature':
	related attachment to triangulate (attestation|sbom|signature|digest), default signature (sbom is deprecated)

Global Flags:
      --output-file string   log output to a file
  -t, --timeout duration     timeout for commands (default 3m0s)
  -d, --verbose              log debug output

$ ./cosign triangulate --type=digest gcr.io/projectsigstore/cosign:v1.13.0
gcr.io/projectsigstore/cosign@sha256:398f441c46e58906dc6d3aaaad22fe63f018dc30acbe13b326e5a016e711301c
```

Screenshot 2023-10-17 at 09 25 40

**Review by haydentherapper — DISMISSED** [review]
Looks great, thank you!

**Comment by haydentherapper** [comment]
Can you run `make docgen`?

**Review by haydentherapper — DISMISSED** [review]
Looks good! Not sure why linter is failing, trying to rerun

**Comment by haydentherapper** [comment]
@cpanato Any guesses why the linter is complaining? we're using the latest golangci-lint version

**Comment by garethahealy** [comment]
@haydentherapper ; ran linting locally that highlighted an indenting issue - fixed and pushed, hopefully that fixes linting.

**Comment by cpanato** [comment]
it is all good on the ci side :)

**Review by haydentherapper — APPROVED** [review]

**Pull request merged**
