### PR TITLE
Bump Fulcio client lib and use LegacyClient

### PR DESCRIPTION
**Pull request by nsmith5**
####  Summary

With @bobcallaway's recent work the client in Fulcio library was renamed to LegacyClient. This change bumps the Fulcio package version and uses that new LegacyClient name. Once GRPC is rolled out in production we should move off of this client as it uses the v1 API's

### CODE REVIEW

**Review by mattmoor — COMMENTED** [review]
I think `.fulcioverifier.go.swp` is unintended?

**Comment by nsmith5** [comment]
Yup, removed and need a mod tidy as well

**Review by mattmoor — DISMISSED** [review]

**Comment by nsmith5** [comment]
Hmm I see the GRPC refactor did pull in some banned dependencies (trillian + grpc middleware) that work against our slimming down the cosign binary....

Should we make a `client` library upstream and not use the `api` package so we can slim down the client library as much as possible?

**Comment by haydentherapper** [comment]
I removed `"github.com/google/certificate-transparency-go"` in the embedded SCT PR, we need to depend on it.

**Comment by nsmith5** [comment]
Ah ok, yeah I don't think we can run away from depending on grpc either now so these changes make sense then..

**Comment by haydentherapper** [comment]
I wonder if the issue is the same thing I was running into in https://github.com/sigstore/cosign/pull/1731/, where one of the Trillian packages defines a flag that conflicts with what's defined in cosignd.

**Comment by haydentherapper** [comment]
This is why in https://github.com/sigstore/cosign/pull/1731/ I copied in a file, so that when I used that package, I was only pulling in the bare minimum.

**Comment by nsmith5** [comment]
closing in favour of #1762

**Pull request closed without merging**
