### PR TITLE
FUN.md broke when RecordObj changed to HashedRecordObj

### PR DESCRIPTION
**Pull request by MitchellJThomas**
The breakage occurred sometime on or before version 1.6

This is a proposed fix for issue #1632

Note: the proposed commit is signed using Level 11 (yes!)

#### Summary
Switch the jq command to use the HashedRecordObj value

#### Release Note
```release-note
Update the instructions for fetching the sig and cert in the FUN.md file. 
```

### CODE REVIEW

**Comment by cpanato** [comment]
@MitchellJThomas please sign the DCO, thanks for this update!

**Comment by MitchellJThomas** [comment]
> @MitchellJThomas please sign the DCO, thanks for this update!

You are welcome.

**Comment by MitchellJThomas** [comment]
Seems I kinda goofed with the `git rebase HEAD~3 --signoff` as it added in commit 9fb9a3448dc5d0fd6bb65790af43d0241dc7f9e1. (embarasing)

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
Theres a weird e2e flake that looks to be an internal github error, but this is a doc only change so I'm not going to retry it.

**Pull request merged**
