### PR TITLE
Changelog for 0.1.0 release!

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by justaugustus** [comment]
Hey @dlorenc, have you seen the Kubernetes release notes generator?

https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md

**Comment by dlorenc** [comment]
Ahhh amazing.

**Review by font — APPROVED** [review]

**Comment by jglick** [comment]
or Release Drafter as GH Action

**Review by priyawadhwa — APPROVED** [review]
Yay!

**Comment by dlorenc** [comment]
Friday nights are the best time to release right? 🚀

**Pull request merged**
