### PR TITLE
Update github.com/google/go-containerregistry/pkg/authn/k8schain module to f1b065c6cb3d

### LINKED ISSUE #1878: [cosigned] Cosigned does not use the provided imagePullSecret for GCR when running in GCP
**Description**

I have private images in Google Container Registry (GCR) that are signed and want to verify them from k8s clusters running in Google Cloud Platform. The cluster and the images are running in different GCP projects and there is no permissions allowing service account from the one project to access GCR resources in the other. So, I have deployed (following the instructions [here](https://github.com/sigstore/helm-charts/tree/main/charts/cosigned#deploy-cosigned-helm-chart)) cosigned in the k8s clusters and both - defaulting and validations are failing with 
```
UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication: spec.containers[0].image
```

If I disable the webhook, kubelet successfully pulls the image and starts the container, therefore I am sure the credentials provided in the image pull secret are correct. 

I have followed exactly the same steps with [kind](https://github.com/kubernetes-sigs/kind) and AWS clusters with exactly the same image and image pull secret - cosigned is working fine and successfully resolve tags to digests, as well as retrieves the signature. 

I found some pointers in different issues in this repo, and the most prominent pointer seems to be https://github.com/sigstore/sigstore/issues/138#issuecomment-970570459. Additionally, with https://github.com/sigstore/cosign/pull/804 exactly `k8schain` is used. I don't have much experience with this module, but it looks like it discovers the GCP service account on the k8s node and prefer it over the provided image pull secret which looks wrong to me - I would expect the image pull secrets to have higher priority.

**Special notes**:
My observations are limited only to AWS|kind|GCP + GCR. I have not tried different OCI registry provider, but I guess it might fail on AWS+ECR and Azure+ACR.

/cc @mattmoor

### PR DESCRIPTION
**Pull request by vpnachev**
#### Summary

Update github.com/google/go-containerregistry/pkg/authn/k8schain module to f1b065c6cb3d

#### Ticket Link

Fixes #1878 

#### Release Note

```release-note
Fix a bug, where cosigned was not using the provided image pull secret but the Google Service Account available on the node.
```

### CODE REVIEW

**Comment by hectorj2f** [comment]
@vpnachev Please, remember to `--signoff` your commits.

**Comment by hectorj2f** [comment]
@imjasonh @vpnachev I am wondering if we could point to `main` instead, or simply wait for a new release of https://github.com/google/go-containerregistry.

**Comment by imjasonh** [comment]
> @imjasonh @vpnachev I am wondering if we could point to `main` instead, or simply wait for a new release of https://github.com/google/go-containerregistry.

The good news is, I plan to cut a release of go-containerregistry today.

The bad news is, because k8schain is in its own module, cutting a release of the main module won't cut a release of the k8schain module.

I'd `go get -u github.com/google/go-containerregistry/pkg/authn/k8schain@main` here so you get the latest possible k8schain.

**Comment by vpnachev** [comment]
Actually, I spend several hours today to get the latest version however, this seems impossible to me right now because k8schain requires `k8s.io/*` v0.24.0, however the knative.dev/pkg is not compatible with it. 



> @vpnachev Please, remember to `--signoff` your commits.

Done.

**Pull request merged**
