### PR TITLE
Update Dockerfile section of README

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Signed-off-by: Alex Cameron <asc@tetsuo.sh>

#### Summary
Update the Dockerfile section of the README.

#### Release Note
NONE.

### CODE REVIEW

**Review by developer-guy — APPROVED** [review]
LGTM

**Review by hectorj2f — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Comment by tetsuo-cpp** [comment]
> I am not following what this change is achieving, why is the extra FROM needed and why are we introducing another registry?

My understanding is that the second FROM is the base image for this Dockerfile. It's a minimal container that has just enough to run the Cosign binary.

As for why I've changed the registry, the infrastructure has been moved from [distroless](https://github.com/distroless) to [chainguard-images](https://github.com/chainguard-images). If you click through to the distroless GitHub org, there is some advice in the README that says:

> Distroless images have moved to the [Chainguard Images](https://github.com/chainguard-images) repo.

> Please update any image references to use the cgr.dev/chainguard registry i.e. `docker pull distroless.dev/static` is now `docker pull cgr.dev/chainguard/static`.

**Comment by lukehinds** [comment]
It was at ghcr.io before though?

**Comment by tetsuo-cpp** [comment]
> It was at ghcr.io before though?

Ah right. Perhaps the images are pushed to both registries? In any case, `cgr.dev` is the one listed in the README of the [image repo](https://github.com/chainguard-images/static).

**Comment by lukehinds** [comment]
My two cents is we should dog food here, build code on gh, push to ghcr, and recommend users pull from ghcr. I don't see a lot of value of introducing another layer of infra.

**Comment by lukehinds** [comment]
Ok, I got it, distroless has been shift and lifted over to chainguard. T.I.L.

**Pull request merged**
