### PR TITLE
DNM: Increase timeout of e2e tests

### PR DESCRIPTION
**Pull request by haydentherapper**

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]

**Comment by haydentherapper** [comment]
I'm thinking what happened is the two new tests, which take 30 seconds each, pushed us over the line of 10 minutes for all tests. Obviously this is not acceptable, we need to revisit not just the e2e tests but the unit tests too.

**Comment by haydentherapper** [comment]
@hectorj2f When I run this locally, each new e2e test takes about 30 seconds, so I would expect to see an extra minute added. Normally the GHA step for running the tests takes about 17 minutes, but it looks like it's taking >25. Any ideas? I had thought the registry might not be faked for e2e tests, but it appears to be.

**Comment by haydentherapper** [comment]
Previous test runs took ~140s, this one took ~890s.

**Review by lukehinds — APPROVED** [review]

**Comment by hectorj2f** [comment]
@haydentherapper We are using a fake registry but the size of the machine and the other running tests in this suite might cause this issues.

**Comment by hectorj2f** [comment]
Perhaps we can run the excessive signatures tests separately from the others.

**Pull request merged**
