### PR TITLE
Add PKCS11 tag in releaser and Makefile for Mac and Windows

### PR DESCRIPTION
**Pull request by garantir-km**
Signed-off-by: Kieran Miller <kieran.miller@garantir.io>

#### Summary
This PR adds the `pkcs11key` tag for both Mac and Windows releases. 
It also creates a new release `linux-pivkey-pkcs11key-amd64` which supports both PIV and PKCS11 keys, and adds its corresponding target `cosign-pivkey-pkcs11key` in the Makefile.

#### Release Note
```release-note
```

### CODE REVIEW

**Comment by dlorenc** [comment]
Cc @cpanato can you take a look at this one?

**Comment by cpanato** [comment]
do we need to generate two binaries one with `pivkey` and another with both `pivkey` and `pkcs11key`, any reason for that? or can we just build one binary with both

**Comment by dlorenc** [comment]
> do we need to generate two binaries one with `pivkey` and another with both `pivkey` and `pkcs11key`, any reason for that? or can we just build one binary with both

I think it should be fine to do one for both.

**Comment by garantir-km** [comment]
Does this look good to you ? @cpanato @dlorenc

**Review by cpanato — APPROVED** [review]
looks great to me
thanks for working on this
/lgtm

**Pull request merged**
