### PR TITLE
add registry options to cosign save

### PR DESCRIPTION
**Pull request by JasonPowr**
#### Summary

This PR closes: https://github.com/sigstore/cosign/issues/3630, it adds registry options to the cosign save cmd, I am fairly certain my changes here are correct, looking for more guidance if needed :) 

#### Release Note

You can now use cosign save with HTTP and Insecure registries, it also includes registry Auth flags etc..
#### Documentation

No docs changes necessary, `cosign save --help` explains everything

### CODE REVIEW

**Comment by cpanato** [comment]
please sign the DCO

**Review by hectorj2f — DISMISSED** [review]
lgtm

**Comment by JasonPowr** [comment]
@cpanato @hectorj2f Any ideas why `CI-Tests / lint (pull_request)` is failing?, I've ran `make lint` and `make golangci-lint` but no changes are applied?

**Comment by hectorj2f** [comment]
@JasonPowr one of the files needs proper formatting https://github.com/sigstore/cosign/pull/3645/files#diff-d0f41cb51f86f43d4cfd386965cd732c22d5d19e46bdac508c4c97e1add895f4R25. That is why it fails. I agree the error is not helping much.

**Comment by JasonPowr** [comment]
@hectorj2f Much Appreciated :)

**Comment by JasonPowr** [comment]
Can I get a re-run on the jobs here, I am unable, the errors don't seem to be related to my changes, just want to see if this is a one off.

**Review by hectorj2f — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Pull request merged**
