### PR TITLE
use default version of intoto pluggable type

### PR DESCRIPTION
**Pull request by bobcallaway**
Instead of explicitly specifying the v0.0.1 type of the intoto rekor type, just use the default version (which is an empty string) and the server will use the preferred implementation.

Fixes: #2219 

Signed-off-by: Bob Callaway <bcallaway@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @asraa

**Review by asraa — DISMISSED** [review]

**Review by priyawadhwa — APPROVED** [review]
LGTM! i think the attestation test probably needs to be updated

**Comment by bobcallaway** [comment]
The fix for this is blocked by https://github.com/sigstore/rekor/issues/1144

**Pull request closed without merging**
