### PR TITLE
feat: load rego policies from OCI images

### LINKED ISSUE #1361: ability to load Rego or CUE policies over OCI registries
**Description**

For example, conftest has the ability to share Rego policies[^1] over OCI registries which means that users can pull or push rego policies to OCI registries, which we can do the same for CUE basically. So, we have support to verify attestation files via Rego or CUE-based policies. To do so, generally, we use file or directory formats to load policies, so, in addition to that, we can basically pull and load them over OCI registries.

```shell
cosign verify-attestation -policy devopps/cue-policies:latest $image

cosign verify-attestation -policy devopps/opa-policies:latest $image
```

[^1]: https://www.conftest.dev/sharing/

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>

#### Summary

You can test this with the following path:
> do not forget to install conftest to push rego policies suitable with their spec

```shell
$ echo "bar" > foo
$ cosign attest --key cosign.key --predicate foo devopps/alpine:3.15.0
$ cat policy.rego
package signature

allow[msg] {
 input.predicate.Data != "bar-test\n"
 msg := sprintf("unexpected data: %v", [input.Data])
}

EOF
$ conftest push --policy policy.rego ghcr.io/developer-guy/policy-rego
2022/02/17 19:23:58 pushing bundle to: ghcr.io/developer-guy/policy-rego:latest
2022/02/17 19:24:01 pushed bundle with digest: sha256:7278b4301eb15f3e16e12d38af512879c1d5df1bd88c7641b094716e7eb7e779

$ cosign verify-attestation --key cosign.pub --policy ghcr.io/developer-guy/policy-rego devopps/alpine:3.15.0
will be validating against Rego policies: [/var/folders/pf/6h9t0mnd4d342ncgpjq_3zl80000gp/T/crane-append3411930157]
There are 1 number of errors occurred during the validation:
- unexpected data: bar

Error: 1 validation errors occurred
main.go:46: error during command execution: 1 validation errors occurred
```

#### Ticket Link

Fixes #1361 

#### Release Note

```release-note
feat: load rego policies from OCI images
```

cc: @Dentrax

### CODE REVIEW

**Comment by dlorenc** [comment]
Sorry I'll get to this one this week!

**Comment by developer-guy** [comment]
Can we re-open this one @dlorenc if you still consider it useful?

**Comment by developer-guy** [comment]
kindly ping @dlorenc @hectorj2f

**Comment by hectorj2f** [comment]
@developer-guy Done!

**Pull request closed without merging**
