### PR TITLE
feat: add ability to override registry keychain

### PR DESCRIPTION
**Pull request by noamichael**
#### Summary

Updates `options.RegistryOptions` to allow users to pass registry credentials via a new type alias `Keychain` which maps to `authn.Keychain`.

Resolves: #1665

#### Ticket Link

Fixes https://github.com/sigstore/cosign/issues/1665

#### Release Note

NONE

### CODE REVIEW

**Comment by noamichael** [comment]
I noticed the linting failed. `gocritic` seems to like `switch` statements over `if/elseif/else` chains. If preferred, I could do

```go
switch {
case o.Keychain != nil:
	opts = append(opts, remote.WithAuthFromKeychain(o.Keychain))
case o.KubernetesKeychain:
	kc := authn.NewMultiKeychain(
		authn.DefaultKeychain,
		google.Keychain,
		authn.NewKeychainFromHelper(ecr.NewECRHelper(ecr.WithLogger(ioutil.Discard))),
		authn.NewKeychainFromHelper(credhelper.NewACRCredentialsHelper()),
		github.Keychain,
	)
	opts = append(opts, remote.WithAuthFromKeychain(kc))
default:
	opts = append(opts, remote.WithAuthFromKeychain(authn.DefaultKeychain))
}
```

but I was trying to make as few changes as possible.

**Comment by dlorenc** [comment]
Seems right, it usually complains after 3 branches.

**Comment by dlorenc** [comment]
Looks like you missed the DCO this time around :)

**Comment by noamichael** [comment]
> Looks like you missed the DCO this time around :)

Sorry about that! I'm not in the habit of signing off on commits. I ended up squashing the history as recommended in the contribution guide. Hopefully any future PRs of mine will be cleaner.

**Comment by dlorenc** [comment]
No worries! The first one is always annoying because I have to keep clicking the GitHub button to allow CI to run in between, after this you'll be able to just rerun yourself!

**Review by dlorenc — APPROVED** [review]

**Comment by ChrisJBurns** [comment]
@noamichael Apologies to bring you back in time 😅  , I have found this PR and wondered how you go this to work in code? I'm using the `SignCmd` in Cosign as a library to sign container images, but am falling into a bit of a hole at the moment with  the fact that Cosign isn't signing anything. Do you know how I would go about creating a Keychain from a registry url, username and password? At the moment, I can't find any examples of doing this

**Comment by noamichael** [comment]
> @noamichael Apologies to bring you back in time 😅 , I have found this PR and wondered how you go this to work in code? I'm using the `SignCmd` in Cosign as a library to sign container images, but am falling into a bit of a hole at the moment with the fact that Cosign isn't signing anything. Do you know how I would go about creating a Keychain from a registry url, username and password? At the moment, I can't find any examples of doing this

It's been awhile! I don't have any working examples, but here is something I just wrote (basically pseudocode) to get the point across on how I expected this to be used. The key point is you need to implement `Keychain` which returns an `Authenticator` which itself returns the `AuthConfig` used to authenticate. The `AuthConfig` has tons of options for logging into a registry. So a `Keychain` is like a factory for `Authenticator`s, which are factories for `AuthConfig`s:

```go
package main

import (
	"fmt"

	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/sigstore/cosign/cmd/cosign/cli/options"
	"github.com/sigstore/cosign/cmd/cosign/cli/sign"
)

// Some struct to hold username and password
type userCredentials struct {
	username string
	password string
}

// A keychain that is able to return the creds based on the registry url
type InMemoryKeyChain struct {
	// An in-memory map of username/passwords
	credentials map[string]userCredentials
}

// Returns a function that is able to produce an AuthConfig struct. This is basically a factory factory
func (k *InMemoryKeyChain) Resolve(resource authn.Resource) (authn.Authenticator, error) {

	// Ask for the registry URL
	registryHost := resource.RegistryStr()

	// Find the user credentials by the registry URL
	userCreds, ok := k.credentials[registryHost]

	if !ok {
		return authn.Anonymous, fmt.Errorf("Unable to find credentials for host %s", registryHost)
	}

	// Return an authConfig that contains the username and password we looked up
	return authn.FromConfig(authn.AuthConfig{
		Username: userCreds.username,
		Password: userCreds.password,
	}), nil
}

func main() {

	// Create a keychain which maps the registry URL to the
	// username and password we use for that registry
	keychain := &InMemoryKeyChain{
		credentials: map[string]userCredentials{
			"registry.example.com": {
				username: "myusername",
				password: "mypassword",
			},
		},
	}

	// OR, if you simply want to use your current host's Docker config,
	// pass authn.DefaultKeychain

	// Call the sign command with all the various flags you need
	sign.SignCmd(
		&options.RootOptions{},
		options.KeyOpts{},
		options.RegistryOptions{
			Keychain: keychain,
		},
		make(map[string]interface{}),
		[]string{"images to sign"},
		"",    // cert path
		"",    // cert chain path
		true,  // upload
		"",    // output signature
		"",    // outputCertificate
		"",    // payloadPath
		true,  // force
		false, // recurisve
		"",    // attachment
		false, // noTlogUpload
	)

}
```

Please let me know if this helps or if you have any more questions!

**Comment by ChrisJBurns** [comment]
@noamichael That worked perfectly! Thank you so much. You've saved me a fair few hours/days trying to figure what I needed to do 😄  I'm trying to take note of all of the things that we currently do that add that extra bit of code so we can make it easier by putting a lot of it in the `pkg` layer making it easier to use as a library. This is definitely one of those areas to make simpler :+1+:

**Pull request merged**
