### PR TITLE
generate and upload release yaml

### LINKED ISSUE #1414: Publish release YAMLs for cosigned
This would make it easier to install directly from CI without needing helm.

cc @n3wscott @mattmoor

### PR DESCRIPTION
**Pull request by k4leung4**
#### Summary

Add workflow that triggers on published release to generate a yaml and upload it to the release for the triggered tag.
The workflow can also be triggered manually that requires the tag to be specified.

#### Ticket Link

Fixes #1414

#### Release Note

```release-note
NONE
```

Signed-off-by: Kenny Leung <kleung@chainguard.dev>

### CODE REVIEW

**Comment by dlorenc** [comment]
That was fast!

**Review by cpanato — COMMENTED** [review]
this will not remove the binaries we push when doing the release? i guess it will just append the new files, but just to make sure :)

**Review by cpanato — COMMENTED** [review]
can this be part of the cloudbuild release job or do we want to run it as action?

**Comment by k4leung4** [comment]
Marking this PR obsolete as it makes more sense to move this into cloudbuild.

Opened PR #1453.

**Pull request closed without merging**
