### PR TITLE
fix: cosign v2.2.1 is incompatible with k8s.io/apiserver version 1.28

### PR DESCRIPTION
**Pull request by vishal-chdhry**
#### Summary

The latest version of API server: `k8s.io/apiserver v0.28.3` uses commit [2695361300d9d6b66602baa8cf366b7212cc9836](https://github.com/kubernetes/kube-openapi/commit/2695361300d9d6b66602baa8cf366b7212cc9836) of `k8s.io/kube-openapi`.
 
Cosign uses the absolute latest commit on kube-openapi  [2dd684a91f00351087fe2f4ed5408d4d2f3775ab](https://github.com/kubernetes/kube-openapi/commit/2dd684a91f00351087fe2f4ed5408d4d2f3775ab).
There is a breaking change in the middle [`406ddbd41478ad8ad12365533a557a629098d102`](https://github.com/kubernetes/kube-openapi/commit/406ddbd41478ad8ad12365533a557a629098d102) causing build issues
```
../../../go/pkg/mod/k8s.io/apiserver@v0.28.3/pkg/server/routes/openapi.go:68:89: cannot use oa.Config (variable of type *common.Config) as *common.OpenAPIV3Config value in argument to builder3.BuildOpenAPISpecFromRoutes
```
I tried to use the commit right before this change but that downgrades cosign:
```sh
$ go get k8s.io/kube-openapi@b017e203322f320d5dd69a3ae04e2ac777025e28
go: downloading k8s.io/kube-openapi v0.0.0-20230920165022-b017e203322f
go: downgraded github.com/sigstore/cosign/v2 v2.2.1 => v2.2.0
go: downgraded k8s.io/kube-openapi v0.0.0-20231010175941-2dd684a91f00 => v0.0.0-20230920165022-b017e203322f
```

This PR downgrades k8s.io/openapi to the commit prior to this breaking change

### CODE REVIEW

**Comment by haydentherapper** [comment]
Given this is an indirect dependency, can you look at the dependency graph and see what’s pulling this in? I want to confirm changing this isn’t going to have any unintended consequences.

**Comment by vishal-chdhry** [comment]
@haydentherapper,

`k8s.io/kube-openapi` is imported by `k8s.io/client-go`

```
- github.com/sigstore/cosign/v2/pkg/cosign/kubernetes
-- k8s.io/client-go/kubernetes
--- k8s.io/client-go/discovery
---- k8s.io/client-go/openapi
```

`k8s.io/client-go v1.28.3`,  the latest stable version (the one we use in cosign v2.2.1) uses an older version of kube-openapi than what we have in the go mod: https://github.com/kubernetes/client-go/blob/9d454d6c3adfb3beb32b38eb692c1688df56c0ec/go.mod#L29

In my PR I have changed it to `k8s.io/kube-openapi v0.0.0-20230816210353-14e408962443` which is slightly newer compared to client-go's.

**Comment by haydentherapper** [comment]
Where are you seeing the build break?

I'd prefer to update `k8s/client-go` to their alpha release or a recent commit rather than update only the indirect dependency, as I thought that was not the preferred practice (though I'm not a go expert).

**Comment by vishal-chdhry** [comment]
@haydentherapper , 

When we bump cosign to 2.2.1 in Kyverno we see failures in build, because `k8s.io/kube-openapi` was also upgraded and the is now incompatible with api server v1.28: https://github.com/kyverno/kyverno/actions/runs/6794902638/job/18472073193
we only support k8s versions 1.25-v1.28 and k8s version 1.29 might have some breaking changes. Thats why we cannot add support for it. 

Also, since it is a alpha release it can have bugs which can also cause problems.

**Comment by hectorj2f** [comment]
@vishal-chdhry We should identify those breaking changes you mentioned. Is there any issue? Based on your latest comment, I'd say kyverno needs to support 1.29 so you can bump cosign version.

**Comment by realshuting** [comment]
Hi @hectorj2f - as @vishal-chdhry mentioned above, we are planning to include this fix in Kyverno 1.11.0 which supports Kubernetes 1.25 - 1.28. Upgrading to 1.29 Kubernetes library in the current Kyverno release could potentially break existing things and it's risky to do so. Ideally we target bumping to Kubernetes 1.29 in the next minor Kyverno release 1.12.0 which is in our roadmap.

**Comment by haydentherapper** [comment]
Closing as noted in https://github.com/sigstore/cosign/pull/3348#pullrequestreview-1722969766

**Pull request closed without merging**
