### PR TITLE
Fix: Add missing schemes to cosign predicate types.

### PR DESCRIPTION
**Pull request by mattmoor**
:bug: As Billy points out in the linked issue these are not RFC 3986 complient as required by the in-toto specification.

This also creates conflicts with validation in `sigstore/policy-controller` downstream because it has started to allow RFC 3986 compliant `predicateType:` in `ClusterImagePolicy`, but these are not, so they are only accessible via their shortnames (and shortnames have proven fraught becaused they change, like this!).

Fixes: https://github.com/sigstore/cosign/issues/2612

/kind bug

#### Release Note

BREAKING: `cosign attest --type {custom|vuln}` (and `cosign verify-attestation`) will now use the RFC 3986 compliant URIs (adds `https://`) so that these predicate types are compliant with the in-toto specification.

### CODE REVIEW

**Review by hectorj2f — DISMISSED** [review]

**Comment by mattmoor** [comment]
I'm updating a couple of the static files here with the following commands:
```
cat pkg/policy/testdata/valid/custom | jq -c ".payload = \"$(cat pkg/policy/testdata/valid/custom  | jq -r .payload | base64 -d | sed 's|cosign.sigstore.dev/attestation/v1|https://cosign.sigstore.dev/attestation/v1|g' | base64)\"" > custom
mv custom pkg/policy/testdata/valid/custom

cat pkg/policy/testdata/valid/vuln | jq -c ".payload = \"$(cat pkg/policy/testdata/valid/vuln  | jq -r .payload | base64 -d | sed 's|cosign.sigstore.dev/attestation/vuln/v1|https://cosign.sigstore.dev/attestation/vuln/v1|g' | base64)\"" > vuln
mv vuln pkg/policy/testdata/valid/vuln
```

**Comment by mattmoor** [comment]
🚨 🚨 Let's not merge this until (at least) Monday 🚨 🚨 

... since I understand I'm sending breaking changes on the weekend, and I'd like to get more 👀 on this.

**Comment by znewman01** [comment]
CC @wlynch 

Supersedes https://github.com/sigstore/cosign/pull/2617

I think I'm okay with merging this for 2.0

**Comment by mattmoor** [comment]
Oh hey, I didn't realize @wlynch had sent a change for this.  That's my bad, happy to go either way.

**Comment by priyawadhwa** [comment]
I'll go ahead and merge this one since I think there's a few minor logging updates included compared to https://github.com/sigstore/cosign/pull/2617

**Pull request merged**
