### PR TITLE
Have the keyless `cosign sign` flow use a single 3LO.

### PR DESCRIPTION
**Pull request by mattmoor**
With this change, the keyless flow builds a single signer for all of the images, which means a single key and 3LO for all of the references we sign:

```shell
$ COSIGN_EXPERIMENTAL=true cosign sign ghcr.io/mattmoor/controller ghcr.io/mattmoor/webhook
Generating ephemeral keys...
Retrieving signed certificate...
Your browser will now be opened to:
https://oauth2.sigstore.dev/auth/auth?REDACTED
Successfully verified SCT...
tlog entry created with index: 693418
Pushing signature to: ghcr.io/mattmoor/controller:sha256-b10f4b2e04cde2e799e080068f162ef668c4db3099382798b5fe1a208023105d.sig
tlog entry created with index: 693420
Pushing signature to: ghcr.io/mattmoor/webhook:sha256-ed1b1c778685ae0739cd4c6354fa2d724351b01e998a019d1ddc2909c377483d.sig
```

Fixes: https://github.com/sigstore/cosign/issues/658
Signed-off-by: Matt Moore <mattomata@gmail.com>

cc @dekkagaijin @dlorenc

### CODE REVIEW

**Review by dekkagaijin — APPROVED** [review]

**Comment by dekkagaijin** [comment]
LGTM once e2e_test.go is updated

**Comment by mattmoor** [comment]
Whoops done

**Review by dekkagaijin — APPROVED** [review]

**Comment by dekkagaijin** [comment]
Also once the latest commit is signed off on 😮‍💨

**Comment by mattmoor** [comment]
Whoops

**Pull request merged**
