### PR TITLE
Beautify help flags

### PR DESCRIPTION
**Pull request by lauchokyip**
Closes https://github.com/sigstore/cosign/issues/2887

Before:
```bash
Attest the supplied blob.

Usage:
  cosign attest-blob [flags]

Examples:
  cosign attest-blob --key <key path>|<kms uri> [--predicate <path>] [--a key=value] [--f] [--r] <BLOB uri>

  # attach an attestation to a blob with a local key pair file and print the attestation
  cosign attest-blob --predicate <FILE> --type <TYPE> --key cosign.key --output-attestation <path> <BLOB>

  # attach an attestation to a blob with a key pair stored in Azure Key Vault
  cosign attest-blob --predicate <FILE> --type <TYPE> --key azurekms://[VAULT_NAME][VAULT_URI]/[KEY] <BLOB>

  # attach an attestation to a blob with a key pair stored in AWS KMS
  cosign attest-blob --predicate <FILE> --type <TYPE> --key awskms://[ENDPOINT]/[ID/ALIAS/ARN] <BLOB>

  # attach an attestation to a blob with a key pair stored in Google Cloud KMS
  cosign attest-blob --predicate <FILE> --type <TYPE> --key gcpkms://projects/[PROJECT]/locations/global/keyRings/[KEYRING]/cryptoKeys/[KEY]/versions/[VERSION] <BLOB>

  # attach an attestation to a blob with a key pair stored in Hashicorp Vault
  cosign attest-blob --predicate <FILE> --type <TYPE> --key hashivault://[KEY] <BLOB>

Flags:
      --bundle string                     write everything required to verify the blob to a FILE
      --certificate string                path to the X.509 certificate in PEM format to include in the OCI Signature
      --certificate-chain string          path to a list of CA X.509 certificates in PEM format which will be needed when building the certificate chain for the signing certificate. Must start with the parent intermediate CA certificate of the signing certificate and end with the root certificate. Included in the OCI Signature
      --fulcio-url string                 address of sigstore PKI server (default "https://fulcio.sigstore.dev")
      --hash string                       hash of blob in hexadecimal (base16). Used if you want to sign an artifact stored elsewhere and have the hash
  -h, --help                              help for attest-blob
      --identity-token string             identity token to use for certificate from fulcio. the token or a path to a file containing the token is accepted.
      --insecure-skip-verify              skip verifying fulcio published to the SCT (this should only be used for testing).
      --key string                        path to the private key file, KMS URI or Kubernetes Secret
      --oidc-client-id string             OIDC client ID for application (default "sigstore")
      --oidc-client-secret-file string    Path to file containing OIDC client secret for application
      --oidc-disable-ambient-providers    Disable ambient OIDC providers. When true, ambient credentials will not be read
      --oidc-issuer string                OIDC provider to be used to issue ID token (default "https://oauth2.sigstore.dev/auth")
      --oidc-provider string              Specify the provider to get the OIDC token from (Optional). If unset, all options will be tried. Options include: [spiffe, google, github, filesystem, buildkite-agent]
      --oidc-redirect-url string          OIDC redirect URL (Optional). The default oidc-redirect-url is 'http://localhost:0/auth/callback'.
      --output-attestation string         write the attestation to FILE
      --output-certificate string         write the certificate to FILE
      --output-signature string           write the signature to FILE
      --predicate string                  path to the predicate file.
      --rekor-url string                  address of rekor STL server (default "https://rekor.sigstore.dev")
      --rfc3161-timestamp-bundle string   path to an RFC 3161 timestamp bundle FILE
      --sk                                whether to use a hardware security key
      --slot string                       security key slot to use for generated key (default: signature) (authentication|signature|card-authentication|key-management)
      --timestamp-server-url string       url to the Timestamp RFC3161 server, default none. Must be the path to the API to request timestamp responses, e.g. https://freetsa.org/tsr
      --tlog-upload                       whether or not to upload to the tlog (default true)
      --type string                       specify a predicate type (slsaprovenance|link|spdx|spdxjson|cyclonedx|vuln|custom) or an URI (default "custom")
  -y, --yes                               skip confirmation prompts for non-destructive operations

Global Flags:
      --output-file string   log output to a file
  -t, --timeout duration     timeout for commands (default 3m0s)
  -d, --verbose              log debug output
```

After 
```bash

 Attest the supplied blob.

Usage:
cosign attest-blob [flags]

Examples:
  cosign attest-blob --key <key path>|<kms uri> [--predicate <path>] [--a key=value] [--f] [--r] <BLOB uri>

  # attach an attestation to a blob with a local key pair file and print the attestation
  cosign attest-blob --predicate <FILE> --type <TYPE> --key cosign.key --output-attestation <path> <BLOB>

  # attach an attestation to a blob with a key pair stored in Azure Key Vault
  cosign attest-blob --predicate <FILE> --type <TYPE> --key azurekms://[VAULT_NAME][VAULT_URI]/[KEY] <BLOB>

  # attach an attestation to a blob with a key pair stored in AWS KMS
  cosign attest-blob --predicate <FILE> --type <TYPE> --key awskms://[ENDPOINT]/[ID/ALIAS/ARN] <BLOB>

  # attach an attestation to a blob with a key pair stored in Google Cloud KMS
  cosign attest-blob --predicate <FILE> --type <TYPE> --key gcpkms://projects/[PROJECT]/locations/global/keyRings/[KEYRING]/cryptoKeys/[KEY]/versions/[VERSION] <BLOB>

  # attach an attestation to a blob with a key pair stored in Hashicorp Vault
  cosign attest-blob --predicate <FILE> --type <TYPE> --key hashivault://[KEY] <BLOB>

Flags:
    --bundle='':
        write everything required to verify the blob to a FILE

    --certificate='':
        path to the X.509 certificate in PEM format to include in the OCI Signature

    --certificate-chain='':
        path to a list of CA X.509 certificates in PEM format which will be needed when building the certificate chain
        for the signing certificate. Must start with the parent intermediate CA certificate of the signing certificate
        and end with the root certificate. Included in the OCI Signature

    --fulcio-url='https://fulcio.sigstore.dev':
        address of sigstore PKI server

    --hash='':
        hash of blob in hexadecimal (base16). Used if you want to sign an artifact stored elsewhere and have the hash

    -h, --help=false:
        help for attest-blob

    --identity-token='':
        identity token to use for certificate from fulcio. the token or a path to a file containing the token is
        accepted.

    --insecure-skip-verify=false:
        skip verifying fulcio published to the SCT (this should only be used for testing).

    --key='':
        path to the private key file, KMS URI or Kubernetes Secret

    --oidc-client-id='sigstore':
        OIDC client ID for application

    --oidc-client-secret-file='':
        Path to file containing OIDC client secret for application

    --oidc-disable-ambient-providers=false:
        Disable ambient OIDC providers. When true, ambient credentials will not be read

    --oidc-issuer='https://oauth2.sigstore.dev/auth':
        OIDC provider to be used to issue ID token

    --oidc-provider='':
        Specify the provider to get the OIDC token from (Optional). If unset, all options will be tried. Options
        include: [spiffe, google, github, filesystem, buildkite-agent]

    --oidc-redirect-url='':
        OIDC redirect URL (Optional). The default oidc-redirect-url is 'http://localhost:0/auth/callback'.

    --output-attestation='':
        write the attestation to FILE

    --output-certificate='':
        write the certificate to FILE

    --output-signature='':
        write the signature to FILE

    --predicate='':
        path to the predicate file.

    --rekor-url='https://rekor.sigstore.dev':
        address of rekor STL server

    --rfc3161-timestamp-bundle='':
        path to an RFC 3161 timestamp bundle FILE

    --sk=false:
        whether to use a hardware security key

    --slot='':
        security key slot to use for generated key (default: signature)
        (authentication|signature|card-authentication|key-management)

    --timestamp-server-url='':
        url to the Timestamp RFC3161 server, default none. Must be the path to the API to request timestamp responses,
        e.g. https://freetsa.org/tsr

    --tlog-upload=true:
        whether or not to upload to the tlog

    --type='custom':
        specify a predicate type (slsaprovenance|link|spdx|spdxjson|cyclonedx|vuln|custom) or an URI

    -y, --yes=false:
        skip confirmation prompts for non-destructive operations

Global Flags:
      --output-file string   log output to a file
  -t, --timeout duration     timeout for commands (default 3m0s)
  -d, --verbose              log debug output
```

#### Summary

Beautify the help flags

#### Release Note

Beautify the help flags with custom printers
#### Documentation

None

### CODE REVIEW

**Comment by znewman01** [comment]
Sorry for the slow review here.

This looks great! I pulled and built and it looks good in my terminal. It will be really easy to make further improvements, too.

My only suggestion: do we want to update our generated/checked-in help text to use this printer as well? That should involve changes to https://github.com/sigstore/cosign/blob/main/cmd/help/main.go

**Comment by znewman01** [comment]
You're probably going to need to run `make docgen` and check in the changed files. Sorry about that, it's an annoying workflow. Also maybe need a rebase against `main` (and the DCO).

After that I'm happy to approve.

**Review by znewman01 — APPROVED** [review]
Thank you so much 🙏

**Review by cpanato — APPROVED** [review]

**Pull request merged**
