### PR TITLE
fix: make tlog entry lookups for online verification shard-aware

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Fixes https://github.com/sigstore/cosign/issues/2294 as described in the issue.

### CODE REVIEW

**Comment by asraa** [comment]
The build here successfully verifies https://github.com/fluxcd/source-controller/issues/899

**Comment by asraa** [comment]
adding a multiple rekor entry blob test real quick

**Comment by asraa** [comment]
all set!

BTW are there any regression tests against OCI container verification with online lookups?

**Review by priyawadhwa — APPROVED** [review]
nice!

**Pull request merged**
