### PR TITLE
`.cosign` -> `.sig`

### LINKED ISSUE #249: Spec: Replace .cosign with .sig in the suffix
See #214 

We should do this before 0.3, maybe support both for a release then go back to just one for 0.4

### PR DESCRIPTION
**Pull request by dekkagaijin**
Fixes #249

Signed-off-by: Jake Sanders <jsand@google.com>

### CODE REVIEW

**Comment by dlorenc** [comment]
Looks like you missed one test.

**Comment by dekkagaijin** [comment]
whoops...

**Review by dlorenc — APPROVED** [review]
We should make sure this one makes it into the CHANGELOG.md too.

**Comment by dekkagaijin** [comment]
> We should make sure this one makes it into the CHANGELOG.md too.

how's this?

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
