### PR TITLE
feat: allows custom key names for import-key-pair

### PR DESCRIPTION
**Pull request by ChrisJBurns**
- the outputted private and public keys that where created when importing key pairs with `--import-key-pair` command where hardcoded to `imported-cosign`. this commit allows for a custom name to be specified using the `--output-key-prefix` or `-o` flag to `--import-key-pair`. example: `--output-key-prefix my-test` leads to `my-test.key` and `my-test.pub` files being outputted. if no `--output-key-prefix` flag is specified, the default `imported-cosign`, so backwards compatibility allowed.
- also changes the `--name` flag in `generate-key-pair` command to `--output-key-prefix` to be more consistent with `import-key-pair`

Closes https://github.com/sigstore/cosign/issues/2586

Signed-off-by: ChrisJBurns <29541485+ChrisJBurns@users.noreply.github.com>

### CODE REVIEW

**Comment by ChrisJBurns** [comment]
Not entirely sure what the `e2e-tests/e2e-kms` are failing? Not sure if it's a change I've made or if it sometimes trips over itself?

Error:
```log
cut: write error: Broken pipe
Error: Process completed with exit code 1.
```

**Comment by znewman01** [comment]
> Not entirely sure what the `e2e-tests/e2e-kms` are failing? Not sure if it's a change I've made or if it sometimes trips over itself?
> 
> Error:
> 
> ```
> cut: write error: Broken pipe
> Error: Process completed with exit code 1.
> ```

Not your fault, don't worry

**Review by znewman01 — APPROVED** [review]

**Review by znewman01 — CHANGES_REQUESTED** [review]
Is there a reason this doesn't match the `--name` from https://github.com/sigstore/cosign/pull/2561 ? I think consistency would be nice here

**Comment by ChrisJBurns** [comment]
> 

Mainly because thought that it may confuse users with the `--key` flag, `--out` describes that it's the output rather than the input that `--name` may suggest. Although, that's purely the way my mind worked when I thought of it, if it's easily understandable to the average user without confusing them, then am happy to change. I guess we can always make the description clear about the differences between `--key` and `--name`?

With a possible `doc` change also? Just to demonstrate the use of both flags? Or do you think the website documentation should just be the `--key` field?

**Comment by znewman01** [comment]
I'd strongly prefer that they match.

Maybe `--key-prefix` across the board would be good? Feel free to modify `generate-key-pair` in this PR too

**Comment by ChrisJBurns** [comment]
Just to ensure I've got the correct understanding, are you saying to change the `--name` in `generate-key-pair` and the `--out` in `import-key-pair` to `--key-prefix`? Leaving the `--key` flag in `import-key-pair` as is?

**Comment by znewman01** [comment]
Thanks for checking!

I'd like `cosign import-key-pair --key-prefix` **and** `cosign generate-key-pair --key-prefix` (so change `generate-key-pair`, and update this PR for `import-key-pair`)

**Comment by ChrisJBurns** [comment]
So:
`cosign generate-key-pair --key-prefix new-keys`
`cosign import-key-pair --key key-to-import.pem --key-prefix new-keys` ?

Apologies, my brains a bit slow this morning 😆

**Comment by znewman01** [comment]
No, my brain's a bit slow. I forgot that `import-key-pair` had a `--key` flag already.

I see the conundrum...let me think

**Comment by znewman01** [comment]
How about `--output-key-prefix`? It's wordy, but it's not a flag you'll use most of the time. So we have:

- `cosign generate-key-pair --output-key-prefix my-cosign` -> `my-cosign.pub`, `my-cosign.key`
- `cosign import-key-pair --key to-import.pem --output-key-prefix my-cosign` -> `my-cosign.pub`, `my-cosign.key`

WDYT? I'm open to other ideas as well, though I'd *really* like to keep the flags identical if possible.

**Comment by ChrisJBurns** [comment]
@znewman01  Yep, I agree with the consistency part. I do wonder if we make `--key` in `cosign import-key-pair --key to-import.pem` to `--key-to-import` ? A bit more wordy but removes a user thinking "What key?" (although they should read the docs, but that assumes devs read docs 😂 ). The only issue with that is the fact that it's a breaking change to the exist `import-key-pair` command as we're changing an existing flag. I'm happy either way though to be honest, I like the `--output-key-prefix` on both import and generate :+1:

**Review by znewman01 — APPROVED** [review]

**Pull request merged**
