### PR TITLE
chore: add rego function to consume modules and evaluate them

### PR DESCRIPTION
**Pull request by hectorj2f**
Signed-off-by: hectorj2f <hectorf@vmware.com>

#### Summary

Add a function that consumes rego policy modules and evaluate them. This would be useful for #1772 work when consuming rego policies and evaluate them.

I also added some unit tests.
#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Review by vaikas — DISMISSED** [review]
nit, the lint warning about dropping the else.

**Comment by vaikas** [comment]
Thanks for doing this!

**Comment by hectorj2f** [comment]
@vaikas This is ready for a review.

**Review by vaikas — APPROVED** [review]
Awesome!

**Pull request merged**
