### PR TITLE
Print message when verifying with old TUF targets

### PR DESCRIPTION
**Pull request by haydentherapper**
#### Summary

This adds console messages when the TUF metadata
used for Rekor or the CTFE key is marked as expired.

I haven't added a log message for Fulcio yet. The way
that certificates are verified is different. Instead of
multiple verifications where we can easily determine
which key successfully verified an object, the x509
library uses a CertPool and returns a valid chain.
I'll need to plumb through the TUF information.

#### Ticket Link

Fixes

#### Release Note

```release-note
Added information when old TUF targets are used to verify signatures
```

### CODE REVIEW

**Comment by haydentherapper** [comment]
Note that this includes the commit from #1467 too. Let me know if you have any feedback on the UX of this. I don't want this to be a scary warning, but I do think users should still be notified.

cc @asraa @dlorenc

**Comment by dlorenc** [comment]
The UX here is fine, is there any way we could make this work for machine readable output too? Maybe include the TUF root we verified against?

**Comment by haydentherapper** [comment]
I'll take a look at piping some information to stdout. Is there any existing format for machine readable output? Just print JSON?

**Comment by dlorenc** [comment]
> I'll take a look at piping some information to stdout. Is there any existing format for machine readable output? Just print JSON?

This can come in a separate PR - but yeah it's typically just when we do --format=json. The basic idea is just that if we feel information is important enough to display to a person, it probably makes sense to make it parseable in a script too.

**Review by asraa — APPROVED** [review]

**Pull request merged**
